version: "3"

services:
  docker-registry:
    restart: on-failure
    image: registry:2
    ports:
      - "5000:5000"
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data
      - REGISTRY_AUTH=token
      - REGISTRY_AUTH_TOKEN_REALM=http://localhost:8080/v1/registry/auth
      - REGISTRY_AUTH_TOKEN_SERVICE=test
      - REGISTRY_AUTH_TOKEN_ISSUER=test
      - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/mnt/local/certs/RootCA.crt
      - REGISTRY_HTTP_TLS_CERTIFICATE=/mnt/local/certs/RootCA.crt
      - REGISTRY_HTTP_TLS_KEY=/mnt/local/certs/RootCA.key
    volumes:
      - "./regdata:/mnt/registry/data"
      - ".devcerts:/mnt/local/certs"